# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
name: 孙福生的博客
title_main: 主页
title: 孙 福 生
subtitle: Android Developer
slogin: "You're unique, nothing can replace you."
email: 1021122748@qq.com
emailname: QQ Mail
description: >
  心中有阳光，脚底有力量！

# the subpath of your site, e.g. /blog/
baseurl: "https://github.com/sfsheng0322/sfsheng0322.github.com/"
# the base hostname & protocol for your site
url: "http://sunfusheng.com/"
cover: "assets/header_image.jpg"
theme_color: "#fc8b3b"
# logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives: 
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Google analytics
# ga_tracking_id: "UA-64640288-1"

# Baidu analytics id:de1df75db196971264bd87815c96f646
bd_tracking_id: ""

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: false                           # Include in the "Share" section of posts
social:

  - name: Weibo
    icon: weibo
    username: 孙福生微博
    url: http://weibo.com/u/3852192525
    desc: Follow me on Weibo
    share: false

  - name: GitHub
    icon: github
    username: 孙福生
    url: https://github.com/sfsheng0322
    desc: Follow me on GitHub
    share: false

  - name: Google+
    icon: google-plus
    username: 孙福生
    url: https://plus.google.com/u/0/107453335221429772724
    desc: Add me to your Circles
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
